name: Publish to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  build_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install wheel
        run: pip install wheel
      - name: Build package
        run: python setup.py bdist_wheel --universal
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_token }}
